# From Previous Lesson

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import math
from sklearn.linear_model import LinearRegression

In [3]:
#this data has been treated with some log transformations like we have seen yesterday
data = pd.read_csv('/content/drive/MyDrive/CURR-v3.X-MAR2023/UNIT1/DAY5/1.08 Linear Regression, TrainTestSplit/regression_data_treated.csv')
data.head()

AVGGIFT   HV1_log  IC1_transformed  IC5_transformed  gender  TARGET_D
0  15.500000  9.510467        17.343389         4.181353    Male      21.0
1   3.080000  6.458590        16.230984         4.150313    Male       3.0
2   7.500000  8.780623        18.047227         4.205057  Female      20.0
3   6.700000  6.200492        11.737110         4.055333    Male       5.0
4   8.785714  7.477123        12.494862         4.088969  Female      10.0

In [4]:
data.rename(columns={'IC1_transformed':'IC1','IC5_transformed':'IC5'},inplace=True)

In [5]:
#separate the features from the labels
y = data['TARGET_D']
X = data.drop(['TARGET_D'], axis=1)

In [6]:
X.head()

AVGGIFT   HV1_log        IC1       IC5  gender
0  15.500000  9.510467  17.343389  4.181353    Male
1   3.080000  6.458590  16.230984  4.150313    Male
2   7.500000  8.780623  18.047227  4.205057  Female
3   6.700000  6.200492  11.737110  4.055333    Male
4   8.785714  7.477123  12.494862  4.088969  Female

In [7]:
#categorical features and numerical ones are going to be treated differently
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = object)

In [8]:
X_cat['gender'].unique()

array(['Male', 'Female', 'U'], dtype=object)

In [ ]:
# Normalizing and Standardizing data - only for numerical variables

In [9]:
X_num.describe().T

count       mean        std       min        25%        50%  \
AVGGIFT  4670.0  11.705325  10.097916  2.260870   7.125938  10.000000   
HV1_log  4670.0   8.036391   1.269845  5.177302   7.233936   7.842845   
IC1      4670.0  15.675380   2.239342  7.707891  14.071580  15.615699   
IC5      4670.0   4.178176   0.052677  3.913190   4.143215   4.177919   

               75%         max  
AVGGIFT  14.333333  450.000000  
HV1_log   8.605080   24.406461  
IC1      17.238244   20.892798  
IC5       4.211933    4.402811

In [10]:
X_num.shape

(4670, 4)

In [11]:
from sklearn.preprocessing import MinMaxScaler # Sets for each colum the minimum = 0 and the maximum = 1
MinMaxtransformer = MinMaxScaler()
MinMaxtransformer.fit(X_num) # fit() Determine the min and the max of each column
x_normalized = MinMaxtransformer.transform(X_num) # .transform() applies the transformation x_normalized will be np.array
print("The type of x_normalized is {} and the shape of the array is {}".format(type(x_normalized),x_normalized.shape))
x_normalized = pd.DataFrame(x_normalized,columns=X_num.columns) # Take the column's names from X_num
x_normalized.head()

The type of x_normalized is <class 'numpy.ndarray'> and the shape of the array is (4670, 4)


AVGGIFT   HV1_log       IC1       IC5
0  0.029569  0.225343  0.730798  0.547694
1  0.001829  0.066633  0.646428  0.484300
2  0.011701  0.187388  0.784180  0.596107
3  0.009915  0.053210  0.305593  0.290313
4  0.014573  0.119601  0.363064  0.359010

In [12]:
X_num.describe().T

count       mean        std       min        25%        50%  \
AVGGIFT  4670.0  11.705325  10.097916  2.260870   7.125938  10.000000   
HV1_log  4670.0   8.036391   1.269845  5.177302   7.233936   7.842845   
IC1      4670.0  15.675380   2.239342  7.707891  14.071580  15.615699   
IC5      4670.0   4.178176   0.052677  3.913190   4.143215   4.177919   

               75%         max  
AVGGIFT  14.333333  450.000000  
HV1_log   8.605080   24.406461  
IC1      17.238244   20.892798  
IC5       4.211933    4.402811

In [13]:
x_normalized.describe().T

count      mean       std  min       25%       50%       75%  max
AVGGIFT  4670.0  0.021094  0.022553  0.0  0.010866  0.017285  0.026963  1.0
HV1_log  4670.0  0.148685  0.066037  0.0  0.106954  0.138620  0.178259  1.0
IC1      4670.0  0.604289  0.169841  0.0  0.482649  0.599762  0.722823  1.0
IC5      4670.0  0.541205  0.107588  0.0  0.469801  0.540680  0.610151  1.0

In [14]:
from sklearn.preprocessing import StandardScaler
Standardtransformer = StandardScaler()
Standardtransformer.fit(X_num) # This will obtain the mean and the sd of each column
x_standardized = Standardtransformer.transform(X_num) # Applies the transformation
print("The numpy array looks like this: ",x_standardized)
print("The type of x_normalized is {} and the shape of the array is {}".format(type(x_standardized),x_standardized.shape))
x_standardized = pd.DataFrame(x_standardized,columns=X_num.columns)
x_standardized.head()

The numpy array looks like this:  [[ 0.37582816  1.16095588  0.74494534  0.06032281]
 [-0.85426035 -1.24264752  0.24813711 -0.52897815]
 [-0.41649938  0.58614368  1.05928459  0.51035392]
 ...
 [-0.03684243 -0.51348549  0.02994518  0.02525012]
 [ 0.1282258   0.35089726 -1.0492367  -1.02554166]
 [ 0.61581198  0.68537639  0.77815463  1.48331225]]
The type of x_normalized is <class 'numpy.ndarray'> and the shape of the array is (4670, 4)


AVGGIFT   HV1_log       IC1       IC5
0  0.375828  1.160956  0.744945  0.060323
1 -0.854260 -1.242648  0.248137 -0.528978
2 -0.416499  0.586144  1.059285  0.510354
3 -0.495732 -1.445921 -1.758861 -2.332225
4 -0.289161 -0.440469 -1.420443 -1.693638

In [15]:
x_standardized.describe().T

count          mean       std       min       25%       50%  \
AVGGIFT  4670.0 -8.292201e-17  1.000107 -0.935388 -0.453547 -0.168897   
HV1_log  4670.0 -9.182281e-16  1.000107 -2.251767 -0.631999 -0.152434   
IC1      4670.0  7.303223e-16  1.000107 -3.558340 -0.716269 -0.026654   
IC5      4670.0 -1.547903e-14  1.000107 -5.030900 -0.663751 -0.004879   

              75%        max  
AVGGIFT  0.260280  43.409118  
HV1_log  0.447889  12.892773  
IC1      0.697987   2.330138  
IC5      0.640906   4.264836

In [16]:
pd.concat([X_num,x_normalized,x_standardized],axis=1)

AVGGIFT   HV1_log        IC1       IC5   AVGGIFT   HV1_log       IC1  \
0     15.500000  9.510467  17.343389  4.181353  0.029569  0.225343  0.730798   
1      3.080000  6.458590  16.230984  4.150313  0.001829  0.066633  0.646428   
2      7.500000  8.780623  18.047227  4.205057  0.011701  0.187388  0.784180   
3      6.700000  6.200492  11.737110  4.055333  0.009915  0.053210  0.305593   
4      8.785714  7.477123  12.494862  4.088969  0.014573  0.119601  0.363064   
...         ...       ...        ...       ...       ...       ...       ...   
4665  15.500000  8.635841  15.280561  4.187901  0.029569  0.179859  0.574344   
4666  11.857143  9.702136  15.029617  4.248632  0.021433  0.235311  0.555311   
4667  11.333333  7.384414  15.742430  4.179506  0.020263  0.114779  0.609374   
4668  13.000000  8.481928  13.326031  4.124159  0.023985  0.171855  0.426104   
4669  17.923077  8.906619  17.417748  4.256304  0.034981  0.193941  0.736437   

           IC5   AVGGIFT   HV1_log       IC1       IC5  
0     0.547694  0.375828  1.160956  0.744945  0.060323  
1     0.484300 -0.854260 -1.242648  0.248137 -0.528978  
2     0.596107 -0.416499  0.586144  1.059285  0.510354  
3     0.290313 -0.495732 -1.445921 -1.758861 -2.332225  
4     0.359010 -0.289161 -0.440469 -1.420443 -1.693638  
...        ...       ...       ...       ...       ...  
4665  0.561069  0.375828  0.472116 -0.176329  0.184646  
4666  0.685104  0.015036  1.311911 -0.288402  1.337647  
4667  0.543921 -0.036842 -0.513485  0.029945  0.025250  
4668  0.430881  0.128226  0.350897 -1.049237 -1.025542  
4669  0.700774  0.615812  0.685376  0.778155  1.483312  

[4670 rows x 12 columns]

# Lesson 1.08

In [ ]:
# Activity 1
# Discussion on categorical variables: how would you currently handle categories? Should you have many or few?

# Lesson 1 : categorical variables

In [24]:
X_cat = data.select_dtypes(include = object)

In [25]:
# in this case there is only one categorical variable
X_cat.head()

gender
0    Male
1    Male
2  Female
3    Male
4  Female

In [26]:
X_cat['gender'].value_counts()

Female    2664
Male      1895
U          111
Name: gender, dtype: int64

In [39]:
#one hot encoding is a way to turn categorical variables into multiple numerical columns
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoder.fit(X_cat) # This determines how many unique values has each categorical column
print(encoder.categories_)
encoded = encoder.transform(X_cat).toarray()
#print(encoded)
#onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
onehot_encoded.head(20)

[array(['Female', 'Male', 'U'], dtype=object)]


gender_Female  gender_Male  gender_U
0             0.0          1.0       0.0
1             0.0          1.0       0.0
2             1.0          0.0       0.0
3             0.0          1.0       0.0
4             1.0          0.0       0.0
5             0.0          1.0       0.0
6             1.0          0.0       0.0
7             0.0          1.0       0.0
8             1.0          0.0       0.0
9             1.0          0.0       0.0
10            1.0          0.0       0.0
11            1.0          0.0       0.0
12            0.0          1.0       0.0
13            1.0          0.0       0.0
14            1.0          0.0       0.0
15            1.0          0.0       0.0
16            1.0          0.0       0.0
17            0.0          0.0       1.0
18            1.0          0.0       0.0
19            1.0          0.0       0.0

In [40]:
#because one of the variables can be deduced from the others, no point in keeping all these columns around
onehot_encoded = onehot_encoded.drop(['gender_Female'],axis=1)
onehot_encoded.head()

gender_Male  gender_U
0          1.0       0.0
1          1.0       0.0
2          0.0       0.0
3          1.0       0.0
4          0.0       0.0

In [41]:
#label encoding keeps just one column and makes it numerical, but watch out: you may be introducing unintended semantics
#if you want to contriol which nuber gets assigned to which category, you can use OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoder.fit(X_cat)
X_cat_trans = label_encoder.transform(X_cat) # ordered wrt value counts
X_cat_trans = pd.DataFrame(X_cat_trans,columns=X_cat.columns)
display(X_cat_trans.head(20))
X_cat_trans['gender'].value_counts()

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


gender
0        1
1        1
2        0
3        1
4        0
5        1
6        0
7        1
8        0
9        0
10       0
11       0
12       1
13       0
14       0
15       0
16       0
17       2
18       0
19       0

0    2664
1    1895
2     111
Name: gender, dtype: int64

In [ ]:
#my_dict = {'Toyota':1,'Audi':1.5,'BMW':1.65}
#def replace_labels(x):
#    my_dict = {'Female':0,'Male':1,'U':2}
#    x = my_dict[x]
#    return x

#df['gender_new'] = df['gender'].apply(replace_labels)
#df['gender_new'] = list(map(replace_lables,df['gender'])) 

In [ ]:
# Activity 2
# do it yourself. Which one do you think is more appropriate here?

# Lesson 2 : train-test split

In [42]:
# let's merge all this information together into a single dataset with all features, now numerical
X = pd.concat([x_normalized, onehot_encoded], axis=1)

In [43]:
X.head()

AVGGIFT   HV1_log       IC1       IC5  gender_Male  gender_U
0  0.029569  0.225343  0.730798  0.547694          1.0       0.0
1  0.001829  0.066633  0.646428  0.484300          1.0       0.0
2  0.011701  0.187388  0.784180  0.596107          0.0       0.0
3  0.009915  0.053210  0.305593  0.290313          1.0       0.0
4  0.014573  0.119601  0.363064  0.359010          0.0       0.0

In [44]:
y = data['TARGET_D']
y.head()

0    21.0
1     3.0
2    20.0
3     5.0
4    10.0
Name: TARGET_D, dtype: float64

In [45]:
# train test split is the way ML generates its claim to fame: 
# we build the model on a portion of the data but we then validate it in 
# another "fresh" portion
# our model has no opportunity to "cheat": it must accurately guess the values 
# in the "fresh" dataset that it never saw before
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3736, 6)
(934, 6)
(3736,)
(934,)


In [47]:
X_train.head()

AVGGIFT   HV1_log       IC1       IC5  gender_Male  gender_U
2858  0.013711  0.122383  0.784180  0.596107          0.0       0.0
4238  0.012499  0.126146  0.633440  0.562500          1.0       0.0
831   0.011887  0.147172  0.826925  0.776779          1.0       0.0
2285  0.013252  0.112634  0.504109  0.570522          0.0       0.0
1417  0.009468  0.175662  0.800766  0.604974          1.0       0.0

In [48]:
y_train.head()

2858     5.0
4238    10.0
831     10.0
2285    11.0
1417    10.0
Name: TARGET_D, dtype: float64

In [49]:
#we train/fit our model like yesterday
lm = LinearRegression()
lm.fit(X_train,y_train)



LinearRegression()

In [50]:
from sklearn.metrics import r2_score
y_pred_train = lm.predict(X_train)
r2_score(y_train, y_pred_train)

0.8617916442966341

In [51]:
# But now we evaluate it in the TEST portion of the data, that we did not use for training.
# This way we know our model is genuinely guessing our donations, not just repeating the values it has seen in the training data


y_pred_test = lm.predict(X_test)
r2_score(y_test, y_pred_test)

0.7835732034742455

In [52]:
y_pred_test

array([ 1.50439417e+01,  1.14513752e+01,  2.07847735e+01,  9.73320677e+00,
        3.25016748e+01,  8.28288383e+00,  2.49319882e+01,  9.35842613e+00,
        1.16465936e+01,  1.82452416e+01,  2.90416859e+01,  2.10173570e+01,
        1.65621651e+01,  1.20793855e+01,  6.49987711e+00,  1.37887827e+01,
        1.09934622e+01,  1.05264089e+01,  6.37095000e+00,  1.11328633e+01,
        2.25286228e+01,  2.56705015e+01,  1.74320042e+01,  8.78760236e+00,
        1.31042196e+01,  1.18216706e+01,  3.79650252e+00,  1.96573266e+01,
        1.07676279e+01,  9.66658724e+00,  1.16873275e+01,  1.28613426e+01,
        1.86373091e+01,  1.88283362e+01,  1.30880278e+01,  1.67478130e+01,
        2.86934804e+00,  5.19817031e+00,  1.20018340e+01,  7.69066801e+00,
        2.78354100e+01,  1.94426727e+01,  7.31925315e+00,  3.55392669e+00,
        1.65823575e+01,  8.78590611e+00,  1.18678242e+01,  6.13689601e+00,
        1.42593992e+01,  1.34271125e+01,  3.04884122e+01,  1.98127893e+01,
        8.36257496e+00,  

In [53]:
from sklearn.metrics import mean_squared_error
# Comptuing the RMSE -> root mean squared error.
np.sqrt(mean_squared_error(y_test,y_pred_test))

4.55961612677076

In [54]:
rmse=np.sqrt(mean_squared_error(y_test,y_pred_test))
rmse

4.55961612677076

In [ ]:
# to make predictions on the new data, 
# we have to process the data (X features) in the same way. 

In [62]:
# Activity 3a
# take the file "data_to_predict" and find out how much those donors could be worth
# watch out: is the data in the same format as what your training data currently looks like?
data_for_p = pd.read_csv('/content/drive/MyDrive/CURR-v3.X-MAR2023/UNIT1/DAY5/1.08 Linear Regression, TrainTestSplit/data_to_predict.csv')
display(data_for_p.head())

AVGGIFT   HV1_log  IC1_transformed  IC5_transformed  gender
0   8.714286  7.209011        17.666103         4.166268    Male
1  16.500000  9.317831        17.358310         4.224620    Male
2  15.100000  8.402447        14.627447         4.186322    Male
3   4.848485  6.440114        12.270634         4.144954  Female
4  19.000000  8.607769        17.977822         4.280958  Female

In [63]:
data_for_p.rename(columns={'IC1_transformed':'IC1','IC5_transformed':'IC5'},inplace=True)

In [64]:
#making the new data look like the transformed one may not be the most immediate exercise...

#we make the same separation into numerical and categorical
X_for_p_num = data_for_p.select_dtypes(include = np.number)
X_for_p_cat = data_for_p.select_dtypes(include = object)



In [65]:
X_for_p_cat.head()

gender
0    Male
1    Male
2    Male
3  Female
4  Female

In [66]:
X_for_p_cat.shape

(31, 1)

In [67]:
# for normalization and one hot encoding we need to make sure we remain consisten with the training data:
# If we MinMax scale just this piece of data, a "1" in this dataset means something very different from a 1 in the original dataset
# If we one-hot-encode in this dataset, the order of the columns (Unknown, Male, Female) may turn out different
#to avoid this, we use the same transformers we had already defined before, we do not fit them again.
encoded_for_p = encoder.transform(X_for_p_cat).toarray()
encoded_for_p
encoder.categories_
onehot_encoded_for_p = pd.DataFrame(encoded_for_p,columns=encoder.get_feature_names_out())
onehot_encoded_for_p = onehot_encoded_for_p.drop(['gender_Female'],axis=1)
onehot_encoded_for_p.head()

gender_Male  gender_U
0          1.0       0.0
1          1.0       0.0
2          1.0       0.0
3          0.0       0.0
4          0.0       0.0

In [68]:
X_for_p_num.head()

AVGGIFT   HV1_log        IC1       IC5
0   8.714286  7.209011  17.666103  4.166268
1  16.500000  9.317831  17.358310  4.224620
2  15.100000  8.402447  14.627447  4.186322
3   4.848485  6.440114  12.270634  4.144954
4  19.000000  8.607769  17.977822  4.280958

In [69]:
X_for_p_normalized = MinMaxtransformer.transform(X_for_p_num)
X_for_p_normalized = pd.DataFrame(X_for_p_normalized,columns=X_for_p_num.columns)

#merge back all of our labels
X_for_p = pd.concat([X_for_p_normalized, onehot_encoded_for_p], axis=1)

X_for_p.head()

AVGGIFT   HV1_log       IC1       IC5  gender_Male  gender_U
0  0.014413  0.105658  0.755274  0.516885          1.0       0.0
1  0.031802  0.215326  0.731929  0.636063          1.0       0.0
2  0.028675  0.167722  0.524809  0.557843          1.0       0.0
3  0.005779  0.065672  0.346058  0.473354          0.0       0.0
4  0.037386  0.178399  0.778916  0.751127          0.0       0.0

In [70]:
#predict and inspect results
results_for_p = lm.predict(X_for_p)

pd.concat([data_for_p,pd.Series(results_for_p)],axis=1).head()

AVGGIFT   HV1_log        IC1       IC5  gender          0
0   8.714286  7.209011  17.666103  4.166268    Male   5.780060
1  16.500000  9.317831  17.358310  4.224620    Male  24.332125
2  15.100000  8.402447  14.627447  4.186322    Male  19.744952
3   4.848485  6.440114  12.270634  4.144954  Female   4.233038
4  19.000000  8.607769  17.977822  4.280958  Female  14.457210

# Lesson 3 : metrics

In [71]:
from sklearn.metrics import mean_absolute_error, r2_score

In [72]:
mae = mean_absolute_error(y_test, y_pred_test)
print(mae)

3.4349568786234137


In [73]:
mse = mean_squared_error(y_test, y_pred_test)
rmse = math.sqrt(mse)
print(rmse)

4.55961612677076


In [74]:
r2 = r2_score(y_test, y_pred_test)
r2

0.7835732034742455

In [75]:

df = pd.DataFrame([['a','c'],['b','d'],['a','e']],columns=['col1','col2'])

In [76]:
df

col1 col2
0    a    c
1    b    d
2    a    e

In [ ]:
encoder = OneHotEncoder().fit(df)
encoded_for_p = encoder.transform(df).toarray()
encoded_for_p
encoder.categories_
cols = [colname for row in encoder.categories_ for colname in row]
cols
onehot_encoded_for_p = pd.DataFrame(encoded_for_p, columns=cols)
cols_to_drop = [row[0] for row in encoder.categories_]
cols_to_drop
onehot_encoded_for_p = onehot_encoded_for_p.drop(cols_to_drop,axis=1)
onehot_encoded_for_p.head()

b    d    e
0  0.0  0.0  0.0
1  1.0  1.0  0.0
2  0.0  0.0  1.0

In [ ]:
cols=[]
for row in encoder.categories_:
    for colname in row:
        cols.append(colname)
cols

['a', 'b', 'c', 'd', 'e']

In [ ]:
# even simpler, without the list comprehensions:
encoder2 = OneHotEncoder(drop='first').fit(df)
encoded_for_p2 = encoder.transform(df).toarray()
#encoded_for_p2
cols = encoder2.get_feature_names(input_features=df.columns)
# Note: in version 1.2 and higher of sklearn this method is called 'get_feature_names_out()'
#cols
onehot_encoded_for_p2 = pd.DataFrame(encoded_for_p2, columns=cols)
onehot_encoded_for_p2.head()

col1_b  col2_d  col2_e
0     0.0     0.0     0.0
1     1.0     1.0     0.0
2     0.0     0.0     1.0